### PR TITLE
add case_insensitive

### PR DESCRIPTION
**Pull request by hansoljin**
This edit makes all commands case insensitive (with one catch that I found. Explained in a bit). This was done by adding `case_insensitive=True` to kurisu.py.

This also caused a bug in assistance cog, where each of the aliases in sr would clash, and caused the cog to not load. No longer necessary anyway, so I removed all the aliases, leaving only "sr" intact.

Catch: invite filters do not work with case_insensitive. I assume it is because the invite filter is separate from the bot, but I wasn't able to resolve it. Please let me know of any suggestions.

### CODE REVIEW

**Comment by bleck9999** [comment]
Could just always make name lowercase when it checks, so for example `invite = await self.bot.invitefilter.fetch_invite_by_alias(alias=name)` (L1610) to `invite = await self.bot.invitefilter.fetch_invite_by_alias(alias=name.lower())`.
If you do it's worth making sure any new invites added are lowercase (see manager.py, InviteFilterManager.add()) as well. Currently they're all lowercase anyway but changing assistance.py would make it so a non-lowercase invite code would be unusable.

Also not sure if this was intentional or not but you appear to have committed changing `dockerbuild.sh`'s permissions to 644 instead of 755, removing the executable permission.

**Comment by hansoljin** [comment]
I can't seem to change dockerbuild.sh back to 755, what?

The permissions refuse to change. I might need to re-do.

**Comment by hansoljin** [comment]
I'm sorry that took so many commits. Windows hates chmod, apparently.

**Comment by bleck9999** [comment]
This pr must be cursed because every time there's some strange other change: first dockerbuild.sh, then the line endings, and now all blank lines in string literals have vanished.

**Comment by hansoljin** [comment]
Part of this may be because I was working with Windows. It absolutely refused to chmod, whatever I did. I had to re-push the properly chmodded version from WSL's virtual drive, which _can_ do chmod.

I may just redo the commits at this point. It went from a 2-line change to like twenty commits based on Windows and GitHub being an idiot.

**Comment by hansoljin** [comment]
I think I need to redo the PR. I have a feeling I need to re-fork Kurisu as I made the dumb mistake to work in `main`.

**Pull request closed without merging**
