### PR TITLE
Update 90DNS command...

### PR DESCRIPTION
**Pull request by el-emmo**
Update the command  to include a new DNS for the US

### CODE REVIEW

**Comment by FrozenChen** [comment]
It should be more clear where the servers are hosted

**Comment by el-emmo** [comment]
Thank you, is this change enough ?

**Comment by FrozenChen** [comment]
Also if both servers are similar shouldnt you use the server closest to you as the primary dns?

**Comment by el-emmo** [comment]
Uh yes you should, that’s exactly what I wrote in the sentence I added or did I oversee something ? Is that not clear ? If you use the DNS for France as primary while located in the US (and vice versa), the connection might just be slower.

**Comment by pbanj** [comment]
That isn't really how it works. A dns is just hey I have this url, what ip does it belong to. It doesn't mess with downloads speeds and at worst would make a page take a fraction of a second longer to resolve.

**Comment by FrozenChen** [comment]
It would just cause more delay in the the domain resolution(which is just done once), wouldnt affect internet speed, but 
`If you’re not from the USA, make sure to set the second IP address as your primary DNS and the first IP address as your secondary DNS.` 
Sounds like:
if you are not from usa -> use france as primary
instead of `use the closest one to you`, for example if i was from mexico by your message i would have to use the france one as primary when usa server is closer

**Pull request merged**
