### PR TITLE
Updated youtube regex

### PR DESCRIPTION
**Pull request by Jan200101**
previous regex was way too over complicated and did not catch all top level domains

related to #355

### CODE REVIEW

**Comment by FrozenChen** [comment]
Multiple innecesary capturing groups and would cause way too many false positives

**Comment by Jan200101** [comment]
what difference does it make if you capture groups or not? excluding groups doesn't speed up the regex and doesn't hinder any code

and could you state what false positives there would be? I still see this PR as having the superior regex as  the existing one only targets one top level domain, again

**Comment by FrozenChen** [comment]
Your regex doesnt accept any youtube link, doesnt even have to be a link nor a video just have youtube.(.*)/(.*) in it

**Comment by Jan200101** [comment]
youtube does not have a lot of things to link outside of just videos so catching everything is not that big of a deal
and yes it is very permissive but its designed that way to support any top level domain and percent encoding

going back on the first commit
the currently existing regex is way too unspecific and over complicated
image

**Comment by pbanj** [comment]
You know what people who constantly check message logs or get pinged for every message love? Not a bunch of false positives because someone can't take no for an answer.

**Comment by Jan200101** [comment]
its very unlikely a lot of false positives will come up
but if its insisted upon that the regex must be stricter I suggest this
`^(https?\:\/\/)?(www\.)?(youtube\.\w{2,63}\/watch.{14,18}|youtu\.*be\/.{11})`

it makes sure its a video and attempts to catch percent encoding
the top level domain can as long as the shorted currently existing TLDs and the longest it could possibly be

**Comment by FrozenChen** [comment]
also those TLD are no longer given by youtube, all gets redirected to `.com` only way would be the user purposely changing the TLD of the url thats why only `.com` is scanned for

**Comment by Jan200101** [comment]
yes youtube redirects any non .com domain but that doesn't stop people from suggesting Video guides to people who don't know better or 
the current regex works yet its designed to be unmaintainable, clunky and leaves many edge cases

**Pull request closed without merging**
