### PR TITLE
11.14 update to ntrboot command

### PR DESCRIPTION
**Pull request by TheGoofBall64**
a simple update to the .ntrboot command in the assistance.py file for the Nintendo homebrew discord server. putting a more updated picture of compatible flashcards (as well as an easier to understand layout). i also added a description with a link to 3ds.hacks.guide/ntrboot so that people can go there to see a more full list of compatible (and incompatible) flashcards for ntrboot. it also helps with figuring out where to buy each flashcart since 3ds.hacks.guide has links on where to buy each flashcart.

Feel free to change the description below, or remove it entirely if need be

`1518` embed.description = "To see an always up to date list of compatible flashcarts go to https://3ds.hacks.guide/ntrboot"

### CODE REVIEW

**Comment by TheGoofBall64** [comment]
or alternativley, you could replace line `1518` with

```
await self.simple_embed(ctx, """
                                To see an always up to date list of compatible flashcarts, go [here](https://3ds.hacks.guide/ntrboot).
                                """, color=discord.Color.default())
```

**Comment by lilyuwuu** [comment]
Here are my critiques on your chart -- I understand that you copied a lot of the stuff from the _current_ chart but I think it should still be pointed out:
image

**Comment by TheGoofBall64** [comment]
thank you for the corrections. ill fix them

**Comment by TheGoofBall64** [comment]
nope, the (R4i Gold 3DS Deluxe “Starter”) is marked as only 4.2-4.5 firmware on 3ds.hacks.guide for the 3ds firmware. I really don't know what Nintendo and these guys did. but they somehow got a flashcard to work on only specific firmware in a short amount of time. And about everything else, I'm working on it right now

**Comment by TheGoofBall64** [comment]
I'll provide a couple of different versions of the compatibility chart so you guys can switch them out. they are here.(I changed the picture in the pull request to the one I would do.) feel free to recommend any changes to the chart as you want (font changes, etc.). I would recommend fixed (version 2)

[original (don't use!)](https://i.imgur.com/CxRwyUX.png)

[fixed (version 1)](https://imgur.com/a/3oMc80D)

[Fixed (version 2)](https://imgur.com/a/cLKdoj6)

[Fixed (version 3)](https://imgur.com/a/kuN6kpJ)

**Comment by lilyuwuu** [comment]
Second revisions based on the fourth version of your visual:
image

A couple other comments:
> nope, the (R4i Gold 3DS Deluxe “Starter”) is marked as only 4.1-4.5 firmware on 3ds.hacks.guide for the 3ds firmware. I really don't know what Nintendo and these guys did. but they somehow got a flashcard to work on only specific firmware in a short amount of time.

This is most likely misinfo. The DS flashcart portion (the gray cart pictured) is just a standard DS flashcart. The 3DS mode flashcart (gateway clone) likely does only work on 4.1-4.5, but the DS flashcart would work on... well, any 3/DS (unless it was patched in DSi 1.4.5 or 3DS 6.x).
- I'd personally prefer a non-serifed font because the one you use seems too rough. Again, still just me though, maybe your font is more accessible or something.

**Comment by TheGoofBall64** [comment]
ok. i think this is the last time your going to have me change anything. but just in case. here's the link to the fixed one. 

[Fixed (version 5)](https://imgur.com/a/c9fzmzE)

**Comment by TheGoofBall64** [comment]
i really hope this is the last one. sorry for having to change so much

[Fixed (version 6)](https://imgur.com/a/1spsZfz)

**Comment by TheGoofBall64** [comment]
ok. this one really this time. definitely should be the LAST one. I am so sorry

[fixed (version 7 final)](https://imgur.com/a/D1qDhv1)

**Comment by lilyuwuu** [comment]
lgtm

**Pull request merged**
