### PR TITLE
HELPERS ARE NOW ABLE TO WATCH USERS

### PR DESCRIPTION
**Pull request by GlaZedBelmont**

### CODE REVIEW

**Comment by pbanj** [comment]
No fuck you

**Comment by GlaZedBelmont** [comment]
> checks failed, wellllp

**Comment by pbanj** [comment]
You are just the worst

**Comment by GlaZedBelmont** [comment]
https://i.pinimg.com/236x/2b/06/f9/2b06f9b7e9b5e9246262625c2b0e7d08.jpg

**Comment by noirscape** [comment]
For the record, it's failing because pyflakes doesn't work with python 3.8, not with any issues in the PR itself.

**Comment by pbanj** [comment]
Yes we know

**Comment by pbanj** [comment]
Hi helpers, suck my peanuts

**Comment by PhazonicRidley** [comment]
ligma

**Comment by 916253** [comment]
this is an important thing for helpers to have; merged.

**Pull request merged**
