### PR TITLE
Update blahaj - inflation is surely a thing

### PR DESCRIPTION
**Pull request by danny8376**
as per Botman's request

### CODE REVIEW

**Comment by parknich081** [comment]
man fuck you >:(

**Review by lifehackerhansol — APPROVED** [review]
penis lmao

**Comment by TheDrawingCoder-Gamer** [comment]
you beat me to it!

**Comment by parknich081** [comment]
i came up with the variable first for the record but danny beat me to it so i never submitted the pr you better credit me >:( /s

**Comment by FrozenChen** [comment]
Fix this `./cogs/memes.py:578:26: E261 at least two spaces before inline comment`

**Comment by TheDrawingCoder-Gamer** [comment]
confusion - on ikea a shorter blahaj is only $8

**Pull request merged**
