### PR TITLE
Added .arrival

### PR DESCRIPTION
**Pull request by daderplord**
image

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Add this as well to complete it: https://i.imgur.com/ZlwaTUp.gif

And for the sake of consistency with the other two perhaps use imgur for the first one: https://i.imgur.com/kNlrsth.gif

**Review by lifehackerhansol — APPROVED** [review]
Works.

**Comment by lifehackerhansol** [comment]
I guess someone with push access will want to fix whitespaces if Rice doesn't know how lol

**Review by lifehackerhansol — APPROVED** [review]

**Comment by daderplord** [comment]
oh and hansol sorry if you get notified bout this thread

**Review by lifehackerhansol — APPROVED** [review]

**Pull request merged**
