### PR TITLE
Add new nodding command

### PR DESCRIPTION
**Pull request by noirscape**
* New non-critical features are not being added to the master branch. Please check the [new-and-improved](https://github.com/ihaveamac/Kurisu/tree/new-and-improved) branch for the Kurisu rewrite.
* If adding words to the filter list in events.py, make sure all characters are lowercase and consist only of characters in Python [`string.printable`](https://docs.python.org/3/library/string.html).

### CODE REVIEW

**Comment by pbanj** [comment]
Nodding?

**Comment by Jisagi** [comment]
@noirscape Requesting a rename to `:nekobang:`

**Comment by pbanj** [comment]
Fucking weebs

**Comment by architdate** [comment]
@Jisagi but everyone uses `nodding`

**Comment by noirscape** [comment]
@Jisagi Through the power of aliases, it now works.

**Comment by pbanj** [comment]
Still not adding it

**Comment by noirscape** [comment]
Unfortunate, but alright, PR closed (although I was originally leaving this up to repository owners to do this).

**Pull request closed without merging**
