### PR TITLE
New cmds (Meme cmds) + .inori2 restored

### PR DESCRIPTION
**Pull request by arkizenty**
* Added `.goose` https://a-whale.tried-to-do.science/i/i62x.jpg
* Added `.pbanj2` https://a-whale.tried-to-do.science/i/q5a2.gif
* Added `.cosmic` https://imgur.com/V4TVpbC

### CODE REVIEW

**Comment by ihaveamac** [comment]
Images should preferably be hosted on imgur, and use direct links like https://i.imgur.com/V4TVpbC.gifv

**Comment by arkizenty** [comment]
alright, I'll upload over to imgur

**Comment by arkizenty** [comment]
Everything has been uploaded and updated 👍

**Comment by arkizenty** [comment]
Turns out `.inori2` was missing, found the original source of the image and restored it
Screenshot_2019-03-24_08-30-47

**Comment by arkizenty** [comment]
Fixed pr conflicts

**Comment by arkizenty** [comment]
Fixed even more pr conflicts

**Pull request merged**
