### PR TITLE
Remove .inoriquest and check for Helpers+ usage on .r4 and .inoriwarn

### PR DESCRIPTION
**Pull request by Mike15678**

### CODE REVIEW

**Comment by noirscape** [comment]
Why make Helpers only allowed to use rule 4? It seems like a common enough usecase to not have that command helper exclusive and would only complicate the use of this thing for non-helpers, who may run into similar issues where users do not plainly state their question.

**Comment by Mike15678** [comment]
@noirscape Staff have been discussing internally for quite a while now regarding users in assistance channels, more often than not, misusing .inoriquest and .r4, when they could instead simply tell a user to ask their question. Both commands can come off as rude and are quite unwelcoming for new users.
With this PR, Helpers+ can still use .r4 in the event they need to actually enforce that rule for a particular user.
Finally, .inoriquest was determined to be redundant, but making it an alias for .r4 could be done; that would help reduce confusion.

**Comment by noirscape** [comment]
@Mike15678 - I would still argue that this restriction seems awfully pointless and that if users abuse the command to be rude (although I would argue that this is probably not done out of bad faith), staff should be able to manually take care of it instead.

Instead, I'd imagine you'd end up with many confused helpers who don't have the Helper role wondering why they couldn't use the command.

**Comment by FrozenChen** [comment]
Addressed in https://github.com/nh-server/Kurisu/commit/9ecca9e55279f8e5f96b1c9fd61a31314a51ae9d will see how it goes from there

**Pull request closed without merging**
