### PR TITLE
extras: send DM for togglechannel if not an interaction

### PR DESCRIPTION
**Pull request by lifehackerhansol**

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
If I'm not wrong, that was the behaviour pre-hybrid command.

Unless you want to re-add the try-catch XD

**Comment by FrozenChen** [comment]
send_dm_message() already takes care of all that, returns True if it was successful and False if it failed with that return Value

**Comment by lifehackerhansol** [comment]
I didn't even realize it had a return value. I'll just use that instead.

**Comment by FrozenChen** [comment]
The thing we care about is that the message gets through, DMs disabled? just send it to bot-cmds

**Comment by lifehackerhansol** [comment]
In that case, I think I'm going to rewrite this PR. There are other alternatives if going that route.

**Pull request closed without merging**
