### PR TITLE
Added embeds for all meme and cute commands + a new whale command

### PR DESCRIPTION
**Pull request by arkizenty**
added .whale and made embeds for meme and cute commands to make it clean
-arkizenty#7140

### CODE REVIEW

**Comment by ihaveamac** [comment]
You should instead be creating the Embed object in the _meme method.

**Comment by arkizenty** [comment]
I didn't use the _meme method just so it can easily be understand if you get what I mean.

**Comment by ihaveamac** [comment]
All of the commands are calling this method anyway, so to reduce duplicated code, it should be created in there.

**Comment by ihaveamac** [comment]
It also doesn't work in its current state because _meme doesn't accept an embed= keyword arg.

**Comment by arkizenty** [comment]
Oh ok, I'll see what I can do to fix it

**Pull request closed without merging**
