### PR TITLE
Text escaping and various fixes

### PR DESCRIPTION
**Pull request by LightSage**
This PR:
- Removes a bunch of cooldown decorators in cogs/assistance.py and uses `CogMeta.command_attrs` to apply a cog-wide cooldown to cogs/assistance.py (See https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.CogMeta.command_attrs for more information.)
- Fixes netinfo to be non-blocking. (https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean)
- Escapes reasons, role names, name changes in logging text.
- Adds a custom context.
- Replaces the old wii u guide link in the welcome DM message with the NH Wii U guide link.
- Removes print duplication from every cog __init__.
- Removes unnecessary hidden kwarg from some commands.
- Adds a check function for the "staffreq" command.
- Sanitizes output on certain commands.

Let me know if this needs some adjustments. :+1:

### CODE REVIEW

**Comment by pbanj** [comment]
still failing

**Comment by FrozenChen** [comment]
Not all assistance commands need a cooldown, making it cog wide would give all commands inside a cooldown, no?

**Comment by LightSage** [comment]
It'd give every command a cooldown in the cog, yeah. The only commands that I saw that didn't have a cooldown were the tutorial commands, which didn't seem like a huge deal to add the same cooldown to it.

**Comment by FrozenChen** [comment]
you are giving SR a cooldown as well

**Pull request merged**
