### PR TITLE
Add birb alert & edit r10

### PR DESCRIPTION
**Pull request by rsxRi**

### CODE REVIEW

**Comment by rsxRi** [comment]
also updated rule10

**Comment by GlaZedBelmont** [comment]
You probably want to split the changes into 2 separate PRs by the way.

**Comment by MechanicalDragon0687** [comment]
> You probably want to split the changes into 2 separate PRs by the way.

this is how American gov't works. you put something worthwhile into the bill to get it passed.

**Comment by rsxRi** [comment]
> You probably want to split the changes into 2 separate PRs by the way.

there's a reason I didn't :)

**Comment by PhazonicRidley** [comment]
Oh no!
Anyway

**Comment by rsxRi** [comment]
well that was a mistake lmao

**Comment by PhazonicRidley** [comment]
oi fuck you, you're clogging up helpers

**Comment by pbanj** [comment]
Nou. If it won't beak anything, it can be merged

**Comment by PhazonicRidley** [comment]
suck my girl cock pb

**Comment by pbanj** [comment]
> 
> 
> suck my girl cock pb

kiss my sandwich ass,

**Pull request merged**
