### PR TITLE
Update transfer.3ds.md

### PR DESCRIPTION
**Pull request by Botman836**
Updated .transfer

### CODE REVIEW

**Review by Gruetzig — COMMENTED** [review]
welcome to smols grr show, today we grr this pr
1. finalizing link is still there
2. perform a manual homebrew swap is extremely clunky and too detailed
3. no [] used anymore so please remove the () too or readd []

instead I suggest the following(aka recommended solution) :
To access the Homebrew Launcher on the new console, follow `Manually entering Homebrew Launcher` under Other troubleshooting on the [troubleshooting page](https://3ds.hacks.guide/troubleshooting#other-troubleshooting)

**Comment by Botman836** [comment]
> To access the Homebrew Launcher on the new console, follow Manually entering Homebrew Launcher under Other troubleshooting on the troubleshooting page

blame git mobile lmao

**Comment by Gruetzig** [comment]
I wont blame git mobile, its simply a skill issue grrr

**Comment by Botman836** [comment]
> I wont blame git mobile, its simply a skill issue grrr
image

**Comment by Gruetzig** [comment]
sorry botman I overreacted because it looked quite bad

**Pull request closed without merging**
