### PR TITLE
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

### PR DESCRIPTION
**Pull request by GlaZedBelmont**

### CODE REVIEW

**Comment by PhazonicRidley** [comment]
yes i support this pr

**Comment by NightYoshi370** [comment]
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHA

**Comment by pbanj** [comment]
so is there an actual reason for this or you guys just shit posting?

**Comment by PhazonicRidley** [comment]
No i actually want this. this deletes the speak invocation message.

**Comment by pbanj** [comment]
Ya I don't want this.

**Pull request closed without merging**
