### PR TITLE
Fixes huge bug that bans any user who sends a message in two different channels within 20 seconds

### PR DESCRIPTION
**Pull request by xnoe**
Please merge ASAP

### CODE REVIEW

**Comment by bleck9999** [comment]
Doesn't really make much more sense to me to and wf_matches than to or it, since it's never supposed to be anything that doesnt evalute to True surely either operation would be redundant?

**Comment by aspargas2** [comment]
yeah I'm guessing the left operand to the or here was just missing some brackets and a string

**Comment by bleck9999** [comment]
Actually having a look at the diff I think it was a typo, the first wf_matches should instead be lf_matches

**Comment by aspargas2** [comment]
ah, makes sense

**Comment by noirscape** [comment]
why is this a ban anyway? seems a tad... overagressive? wouldn't it be better to mute or probate users instead. that way you'd not have learned about this bug by the fact that several of your members got banned.

**Comment by suchmememanyskill** [comment]
because these kinds of bots sometimes also dm all users after putting a message in all the channels

**Comment by FrozenChen** [comment]
Fixed in eb817f2bc52a835cc39c87793067fe1be5c0312f

**Pull request closed without merging**
